/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidex_MainActivity2 */

#ifndef _Included_com_example_androidex_MainActivity2
#define _Included_com_example_androidex_MainActivity2
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
