/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidex_MainActivity2_BackThread */

#ifndef _Included_com_example_androidex_MainActivity2_BackThread
#define _Included_com_example_androidex_MainActivity2_BackThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_androidex_MainActivity2_BackThread_MIN_PRIORITY
#define com_example_androidex_MainActivity2_BackThread_MIN_PRIORITY 1L
#undef com_example_androidex_MainActivity2_BackThread_NORM_PRIORITY
#define com_example_androidex_MainActivity2_BackThread_NORM_PRIORITY 5L
#undef com_example_androidex_MainActivity2_BackThread_MAX_PRIORITY
#define com_example_androidex_MainActivity2_BackThread_MAX_PRIORITY 10L
/*
 * Class:     com_example_androidex_MainActivity2_BackThread
 * Method:    isDone
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_androidex_MainActivity2_00024BackThread_isDone
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
