/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidex_MainActivity */

#ifndef _Included_com_example_androidex_MainActivity
#define _Included_com_example_androidex_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidex_MainActivity
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_androidex_MainActivity_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_androidex_MainActivity
 * Method:    testString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_androidex_MainActivity_testString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
